### ISSUE TITLE
Fail to install MagicPython in Atom

### ISSUE THREAD

**Issue by pingshunhuangalex** [MagicStack/MagicPython#115]
* **Editor name and version**:
* **Platform**:
```
Atom    : 1.23.0-beta1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
* **Color scheme**:
* **MagicPython version**:
`1.0.12`
* **A sreenshot**:
* **5-10 lines of surrounding code**:
```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\SPHS\.atom\packages\MagicPython\package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (C:\Users\SPHS\AppData\Local\atom\app-1.23.0-beta1\resources\app\apm\node_modules\asar-require\lib\require.js:86:27)
    at C:\Users\SPHS\AppData\Local\atom\app-1.23.0-beta1\resources\app\apm\lib\install.js:476:42
    at fn (C:\Users\SPHS\AppData\Local\atom\app-1.23.0-beta1\resources\app\apm\node_modules\async\lib\async.js:582:34)
    at Immediate.<anonymous> (C:\Users\SPHS\AppData\Local\atom\app-1.23.0-beta1\resources\app\apm\node_modules\async\lib\async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by pingshunhuangalex** [comment]
resolved by installing from console, `apm install magicpython`. I'll leave the ticket open for now. Thanks.

**Comment by elprans** [comment]
This seems like an Atom bug.  There is no code in MagicPython that affects the installation process.

**Comment by elprans** [comment]
Specifically, this: https://github.com/atom/atom/issues/14913

**Comment by mlenzen** [comment]
I think I was having this problem too:
```
$ apm install MagicPython
Installing MagicPython to /home/mike/.atom/packages ✓
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/mike/.atom/packages/MagicPython/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (/usr/share/atom/resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /usr/share/atom/resources/app/apm/lib/install.js:476:42
    at fn (/usr/share/atom/resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

```

I got it to work by changing the capitalization of the package name:

```
$ apm install magicpython
Installing magicpython to /home/mike/.atom/packages ✓

```

I'm pretty sure it used to work with the camel case name

**Comment by pete-heirendt-vacasa** [comment]
Definitely due to case-sensitivity ("**MagicPython**" vs "**magicpython**"), at least for the case I got same error on my machine today.

- OSX Sierra 10.12.6
- Atom 1.23.1

When trying to install from within Atom UI, it fails. 
So next I tried from commandline using apm.

Fails with camel-case "**MagicPython**":
```$ apm install MagicPython
Installing MagicPython to /Users/peteheirendt/.atom/packages ✓
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/Users/peteheirendt/.atom/packages/MagicPython/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:476:42
    at fn (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

Works fine with lower-case "**magicpython**":
$ apm install magicpython
Installing magicpython to /Users/peteheirendt/.atom/packages ✓
```

**Comment by elprans** [comment]
This is an upstream regression.  I've opened an issue there.
