### ISSUE TITLE
Install error with Atom

### ISSUE THREAD

**Issue by sawtell** [MagicStack/MagicPython#118]
I am receiving the following error when installing this package in the Atom editor:

```
$ apm install MagicPython
Installing MagicPython to /Users/user/.atom/packages ✓
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/user/.atom/packages/MagicPython/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/asar-require/lib/require.js:86:27)
    at /Applications/Atom.app/Contents/Resources/app/apm/lib/install.js:476:42
    at fn (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

This occurs with the `apm` command as well as installing via the app itself.

Operating System: OSX 10.11.6
Atom version:
```
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by sawtell** [comment]
Closing.. just tried to install again, this time without camel case (taken from the readme)
`apm install magicpython`

**Comment by elprans** [comment]
This is antivirus-related atom bug.  Dupe of #115 and #113.
